name: vistoria_app
description: "Aplicativo de Vistorias de Boas PrÃ¡ticas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Ãcones padrÃ£o iOS
  cupertino_icons: ^1.0.8

  # ğŸ“¸ Para tirar foto da nÃ£o conformidade
  image_picker: ^1.1.2

  # âœï¸ Para assinatura digital
  signature: ^5.5.0

  # ğŸ§¾ Para gerar PDF
  pdf: ^3.11.0
  printing: ^5.13.5

  # ğŸ’¾ Para salvar arquivos localmente (PDF, imagens)
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
